apiVersion: apps/v1
kind: Deployment
metadata:
  name: imaging-server
  labels:
    app: imaging-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imaging-server
  template:
    metadata:
      labels:
        app: imaging-server
    spec:
      containers:
      - name: imaging-server
        image: ljiho1998/imaging-server
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: imaging-server-svc
spec:
  type: NodePort
  selector:
    app: imaging-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      