apiVersion: apps/v1
kind: Deployment
metadata:
  name: imaging-server
  labels:
    app: imaging-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imaging-server
  template:
    metadata:
      labels:
        app: imaging-server
    spec:
      containers:
      - name: imaging-server
        image: ljiho1998/imaging-server
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: queue-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: queue-default-user
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: imaging-server-svc
spec:
  selector:
    app: imaging-server
  ports:
    - protocol: TCP
      port: 3000
      